name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"  # Gera uma vez por dia
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate the snake
        uses: Platane/snk@v3
        with:
          github_user_name: svlucas7
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push the snake to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
